version: "3.9"
services:
    groc_console:
        build: .
        depends_on:
            - db
    db:
        image: "mcr.microsoft.com/mssql/server"
        ports: 
            - "1401:1433"
        volumes:
            - ./mssql:/var/opt/mssql
        environment:
            SA_PASSWORD: "P@ssword"
            ACCEPT_EULA: "Y"